__title__ = 'spaSmry'
__version__ = '0.1.0'
__summary__ = 'A spaCy v2.0 extension for summarizing text.'
__url__ = 'https://github.com/jdkato/spaSmry'
__author__ = 'Joseph Kato'
__email__ = 'joseph@jdkato.io'
__license__ = 'MIT'
